### ISSUE TITLE
Add space-filling symmetry bug

### ISSUE THREAD

**Issue by ChanaChelem** [uri-raviv-lab/dplus-dev#3]
- add a sphere
- remove the sphere
- try to add space-filling symmetry...

![image](https://user-images.githubusercontent.com/55047726/150948911-ddf1c1b6-8796-49b0-854f-8424bf3c672e.png)

**Comment by TheRand0m1z3r** [comment]
This was tried, but the bug was unreproducible. Therefore, the issue is closed
